AcademicManagement/AcademicManagement/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('admin_general.urls')),
    path('', include('admin_master.urls')),
    path('', include('admin_employee.urls'))
]

AcademicManagement/admin_master/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('departments/', views.department_manage,name="department"),
    path('designation/', views.designation_manage,name="designation"),
    path('qualification/', views.qualification_manage,name="qualification"),
    path('class/', views.class_manage,name="class"),
    path('division/', views.division_manage,name="division"),
    path('employee-category/', views.employee_category_manage,name="employee-category"),
    path('subject/', views.subject_manage,name="subject"),
    path('get_class_details/', views.get_class_details, name='get_class_details'),
    path('update_class_details/', views.update_class_details, name='update_class_details'),
    path('delete_class/', views.delete_class, name='delete_class'),
    path('get_departments_details/', views.get_departments_details, name='get_departments_details'),
    path('update_departments_details/', views.update_departments_details, name='update_departments_details'),
    path('delete_department/', views.delete_department, name='delete_department'),
    path('get_designation_details/', views.get_designation_details, name='get_designation_details'),
    path('update_designation_details/', views.update_designation_details, name='update_designation_details'),
    path('delete_designation/', views.delete_designation, name='delete_designation'),
    path('get_qualification_details/', views.get_qualification_details, name='get_qualification_details'),
    path('update_qualification_details/', views.update_qualification_details, name='update_qualification_details'),
    path('delete_qualification/', views.delete_qualification, name='delete_qualification'),   
    path('get_division_details/', views.get_division_details, name='get_division_details'),
    path('update_division_details/', views.update_division_details, name='update_division_details'),
    path('delete_division/', views.delete_division, name='delete_division'),
    path('get_employee_category_details/', views.get_employee_category_details, name='get_employee_category_details'),
    path('update_employee_category_details/', views.update_employee_category_details, name='update_employee_category_details'),
    path('delete_employee_category/', views.delete_employee_category, name='delete_employee_category'),
    path('get_subject_details/', views.get_subject_details, name='get_subject_details'),
    path('update_subject_details/', views.update_subject_details, name='update_subject_details'),
    path('get_subject_view/', views.get_subject_view, name='get_subject_view'),
    path('delete_subject/', views.delete_subject, name='delete_subject'),




]

AcademicManagement/admin_master/models.py
from django.db import models

# Create your models here.
class AcademicClass(models.Model):
    class_name = models.CharField(max_length=150)
    is_enabled = models.BooleanField(default=True)



class AcademicDepartment(models.Model):
    department_name = models.CharField(max_length=100)
    department_code = models.CharField(max_length=10)
    is_active = models.BooleanField(default=True)


class AcademicDesignation(models.Model):
    designation_name = models.CharField(max_length=100)
    designation_code = models.CharField(max_length=10)
    is_active = models.BooleanField(default=True)


class AcademicQualification(models.Model):
    qualification_name = models.CharField(max_length=150)
    is_active = models.BooleanField(default=True)

class AcademicDivision(models.Model):
    division_name = models.CharField(max_length=150)
    is_active = models.BooleanField(default=True)


class AcademicEmployeeCategory(models.Model):
    EMPLOYEE_CATEGORY_CHOICES = [
        (1, 'Accountant'),
        (4, 'Cafeteria'),
        (2, 'Teacher'),
        (3, 'Library'),
        (5, 'Other'),
    ]


    employee_category_name = models.CharField(max_length=255)
    employee_category_area = models.IntegerField(choices=EMPLOYEE_CATEGORY_CHOICES)
    is_active = models.BooleanField(default=True)


class AcademicSubject(models.Model):
    subject_name = models.CharField(max_length=150)
    classes = models.ManyToManyField('AcademicClass')
    is_active = models.BooleanField(default=True)

AcademicManagement/admin_master/views.py
from django.shortcuts import render,redirect
from .models import AcademicClass,AcademicDepartment,AcademicDesignation,AcademicQualification,AcademicDivision,AcademicEmployeeCategory,AcademicSubject
from django.conf import settings
from django.http import JsonResponse

# Create your views here.
def department_manage(request):
    success_message=None
    error_message = None
    academic_department = AcademicDepartment.objects.all()
    if request.method == 'POST':
        department_name = request.POST.get('department_name','').strip()
        department_code = request.POST.get('department_code','').strip()
        
        # Server-side validation
        if not department_name or not department_code:
            error_message ='Both Department Name and Code are required.'
        elif AcademicDepartment.objects.filter(department_name__iexact=department_name).exists():
            error_message='Department Name already exists.'
        elif AcademicDepartment.objects.filter(department_code__iexact=department_code).exists():
            error_message='Department Code already exists.'
        else:
           
            # Create the department object
            AcademicDepartment.objects.create(
                department_name=department_name,
                department_code=department_code
            )
            success_message='Department added successfully.'

            
    context = {
        'errormessage': error_message,
        'successmessage': success_message,
        'academic_department': academic_department,
    }

    return render(request, 'department_manage.html',context)


def designation_manage(request):
    success_message=None
    error_message = None
    academic_designation = AcademicDesignation.objects.all()
    if request.method == 'POST':
        designation_name = request.POST.get('designation_name','').strip()
        designation_code = request.POST.get('designation_code','').strip()

        if not designation_name or not designation_code:
            error_message ='Both Designation Name and Code are required.'
        elif AcademicDesignation.objects.filter(designation_name__iexact=designation_name).exists():
            error_message='Designation Name already exists.'
        elif AcademicDesignation.objects.filter(designation_code__iexact=designation_code).exists():
            error_message='Designation Code already exists.'
        else:
           
            AcademicDesignation.objects.create(
                designation_name=designation_name,
                designation_code=designation_code
            )

            success_message='Designation added successfully.'

            
    context = {
        'errormessage': error_message,
        'successmessage': success_message,
        'academic_designation': academic_designation,
    }
    return render(request, 'designation_manage.html',context)


def qualification_manage(request):
    success_message=None
    error_message = None
    academic_qualification = AcademicQualification.objects.all()

    if request.method == 'POST':
        qualification_name = request.POST.get('qualification_name', '').strip()

        if not qualification_name:
            error_message = 'Qualification name cannot be empty.'
        else:
            if AcademicQualification.objects.filter(qualification_name=qualification_name).exists():
                error_message = 'Qualification name already exists.'
            else:
                AcademicQualification.objects.create(qualification_name=qualification_name)
                success_message = 'Qualification created successfully.'

    context = {
        'errormessage': error_message,
        'successmessage': success_message,
        'academic_qualifications': academic_qualification,
    }

    return render(request, 'qualification_manage.html', context)

def class_manage(request):
    success_message=None
    error_message = None
    academic_classes = AcademicClass.objects.all()

    if request.method == 'POST':
        class_name = request.POST.get('class_name', '').strip()

        if not class_name:
            error_message = 'Class name cannot be empty.'
        else:
            if AcademicClass.objects.filter(class_name=class_name).exists():
                error_message = 'Class name already exists.'
            else:
                AcademicClass.objects.create(class_name=class_name)
                success_message = 'Class created successfully.'
    
    context = {
        'errormessage': error_message,
        'successmessage': success_message,
        'academic_classes': academic_classes,
    }

    return render(request, 'class_manage.html', context)


def division_manage(request):
    success_message=None
    error_message = None
    academic_division = AcademicDivision.objects.all()

    if request.method == 'POST':
        division_name = request.POST.get('division_name', '').strip()

        if not division_name:
            error_message = 'Division name cannot be empty.'
        else:
            if AcademicDivision.objects.filter(division_name=division_name).exists():
                error_message = 'Division name already exists.'
            else:
                AcademicDivision.objects.create(division_name=division_name)
                success_message = 'Division created successfully.'

    context = {
        'errormessage': error_message,
        'successmessage': success_message,
        'academic_divisions': academic_division,
    }

    return render(request, 'division_manage.html', context)


def subject_manage(request):
    success_message=None
    error_message = None
    academic_classes = AcademicClass.objects.filter(is_enabled=True)
    academic_subject=AcademicSubject.objects.all()
    if request.method == 'POST':
        subject_name = request.POST.get('subject_name')
        class_ids = request.POST.getlist('classes')
        if not subject_name:
            error_message = 'Division name cannot be empty.'
        elif not class_ids:
            error_message = 'Select Class'
        else:
            if AcademicSubject.objects.filter(subject_name=subject_name).exists():
                error_message = 'Subject name already exists.'
            else:
                subject = AcademicSubject.objects.create(subject_name=subject_name)
                subject.classes.set(class_ids)
                subject.save()
                success_message = 'Subject created successfully.'
        


    context={
        'errormessage': error_message,
        'successmessage': success_message,
        "academic_classes":academic_classes,
        "academic_subject":academic_subject
    }
    return render(request,"subject_manage.html",context)

def employee_category_manage(request):
    success_message=None
    error_message = None
    academic_employee_category = AcademicEmployeeCategory.objects.all()

    if request.method == 'POST':
        employee_category_name = request.POST.get('category_name', '').strip()
        employee_category_area = request.POST.get('category_area', '').strip()
        print(type(employee_category_name))
        if not employee_category_name or not employee_category_area:
            error_message = 'Both Employee Name and Area are required.'
        elif AcademicEmployeeCategory.objects.filter(employee_category_name__iexact=employee_category_name).exists():
            error_message = 'Employee Name already exists.'
        elif AcademicEmployeeCategory.objects.exclude(employee_category_area=5).filter(employee_category_area__iexact=employee_category_area).exists():
            error_message = 'Employee Area already exists.'
        else:
            AcademicEmployeeCategory.objects.create(
                employee_category_name=employee_category_name,
                employee_category_area=employee_category_area
            )
            success_message = 'Employee added successfully.'

    context = {
        'errormessage': error_message,
        'successmessage': success_message,
        'academic_employee_categorys': academic_employee_category,
        'settings': settings
    }

    return render(request, 'employee_category_manage.html', context)


#edit view
def get_class_details(request):
    class_id = request.GET['class_id']
    cls_obj=AcademicClass.objects.get(id=class_id)
    print('Received class_id:', cls_obj)
    response_data = {
    'id': cls_obj.id,
    'name': cls_obj.class_name,
    'select': 1 if cls_obj.is_enabled else 0,
    }
    return JsonResponse(response_data)

def update_class_details(request):
    update_id = request.GET['updateId'].strip()
    update_class = request.GET['updateClass'].strip()
    update_Status = request.GET['updateStatus'].strip()
    error_message=None
    success_message=None
    if not update_class:
            error_message = 'Class name cannot be empty.'
    else:
        if AcademicClass.objects.exclude(id=update_id).filter(class_name=update_class).exists():
            error_message = 'Class name already exists.'
        else:
            obj= AcademicClass.objects.get(id=update_id)
            obj.class_name = update_class
            obj.is_enabled=int(update_Status)
            obj.save()
            success_message = 'Class updated successfully.'
    
    
    
    response_data = {
    'errormessage': error_message,
    'successmessage': success_message,
    }
    return JsonResponse(response_data)


def delete_class(request):
    delete_id = request.GET['id'].strip()
    q = AcademicClass.objects.get(id=delete_id)
    q.delete()
    return JsonResponse({"message":"deleted sucess fully"})




#department
def get_departments_details(request):
    department_id = request.GET['department_id']
    dep_obj=AcademicDepartment.objects.get(id=department_id)
    response_data = {
    'id': dep_obj.id,
    'name': dep_obj.department_name,
    'code':dep_obj.department_code,
    'select': 1 if dep_obj.is_active else 0,
    }
    return JsonResponse(response_data)

AcademicManagement/admin_master/templates/employee_category_manage.html
{% extends 'admin_base.html' %}
{% block content %}
{% load static %}
<ul class="breadcrumb">
    <li><a href="#">Home</a></li>     
    <li class="active">Master</li>               
    <li class="active">Employee Categorys</li>
</ul>
<!-- END BREADCRUMB -->                       
<div class="page-title">                    
    <h2><span class="fa fa-arrow-circle-o-left"></span> Manage Employee Categorys</h2>
</div>                   


<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">

    <div class="row">
        <div class="col-md-12">
            
            <form class="form-horizontal" method="post" enctype="multipart/form-data">
                {% csrf_token %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><strong>New </strong> Employee Categorys</h3>
                    <ul class="panel-controls">
                        <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
                    </ul>
                </div>
                <div class="panel-body">                                                                        
                    
                    <div class="row">
                        
                        <div class="col-md-6">
                            
                            <div class="form-group">
                                <div class="col-md-11 col-xs-12">                                                                                                                                                        
                                    <input type="text" name="category_name" required autofocus class="form-control" placeholder="Employee Category Name"/>                                                    
                                </div>
                            </div>
                            
                        </div>
  
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-12 col-xs-12">                                                                                            
                                    <select class="form-control " name="category_area">
                                        <option value="{{ settings.EMPLOYEE_CATEGORY_ACCOUNTANT }}">ACCOUNTANT</option>
                                        <option value="{{ settings.EMPLOYEE_CATEGORY_CAFETERIA }}">CAFTERIA</option>
                                        <option value="{{ settings.EMPLOYEE_CATEGORY_TEACHER }}">TEACHER</option>
                                        <option value="{{ settings.EMPLOYEE_CATEGORY_LIBRARY }}">LIBRARY</option>
                                        <option value="{{ settings.EMPLOYEE_CATEGORY_OTHER }}">OTHER</option>
                                        
                                    </select>
                                </div>
                            </div>
                        </div>
                        
                        
                    </div>

                </div>
                <div class="panel-footer">
                    <input type="reset" value="Clear Form" class="btn btn-default">                                   
                    <button class="btn btn-primary pull-right">Submit</button>
                </div>
            </div>
            </form>
            <div class="panel panel-default">
                <div class="panel-heading">                                
                    <h3 class="panel-title">Default</h3>
                    <ul class="panel-controls">
                        <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
                        <li><a href="#" class="panel-refresh"><span class="fa fa-refresh"></span></a></li>
                        <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
                    </ul>                                
                </div>
                <div class="panel-body">
                    <table class="table datatable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Employee Categorys Name</th>
                                <th>Area</th>
                                <th>Status</th>
                                <th>Action</th>

                            </tr>
                        </thead>
                        <tbody>
                            {% for category in academic_employee_categorys %}
                                <tr id="{{category.id}}">
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ category.employee_category_name }}</td>
                                    <td>{{ category.get_employee_category_area_display }}</td>
                                    <td>
                                        
                                        {% if category.is_active %}
                                            <span class="label label-success">Active</span>
                                        {% else %}
                                            <span class="label label-danger">Deactive</span>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <button class="btn btn-info" onclick="edit_pop_employee_category({{category.id}})">
                                            <span id ="spinner{{category.id}}" class="fa fa-pencil"></span>
                                        </button>
                                        {% if not category.is_active %}
                                        <a onclick="delete_employee_category({{category.id}})">
                                            <button class="btn btn-danger">
                                                <span class="glyphicon glyphicon-trash"></span>
                                            </button>
                                        </a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            
                        </tbody>
                    </table>
                </div>
            </div>
            <input type="hidden" value="{{ request.scheme }}://{{ request.get_host }}/get_employee_category_details/" name="" id="url">
        </div>
        
    </div>

</div>

{% endblock %}
{% block message %}

<div class="message-box animated fadeIn" data-sound="alert" id="mb-remove-row">
    <div class="mb-container">
        <div class="mb-middle">
            <div class="mb-title"><span class="fa fa-times"></span> Remove <strong>Data</strong> ?</div>
            <div class="mb-content">
                <p>Are you sure you want to delete?</p>                    
                <p>Press Yes if you sure.</p>
            </div>
            <div class="mb-footer">
                <div class="pull-right">
                    <input type="hidden" value="{{ request.scheme }}://{{ request.get_host }}/delete_employee_category/" name="" id="deleteurl">
                    <button class="btn btn-success btn-lg mb-control-yes" >Yes</button>
                    <button class="btn btn-default btn-lg mb-control-close">No</button>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Bootstrap 3.x Modal -->
<div class="modal fade" id="modal-default" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="myModalLabel">Edit Employee Category</h4>
        </div>
        <div class="modal-body">
            <div class="row custom-margin-bottom">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-12 col-xs-12">
                            <input type="hidden"  id="edit_id"/>
                            <input type="text" id="edit_name" class="form-control"  placeholder="Employee Category Name"/>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-12 col-xs-12">                                                                                            
                            <select class="form-control " id="edit_area">
                                <option value="1">ACCOUNTANT</option>
                                <option value="4">CAFTERIA</option>
                                <option value="2">TEACHER</option>
                                <option value="3">LIBRARY</option>
                                <option value="5">OTHER</option>
                                
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        
            <div class="row">
                <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-12 col-xs-12">                                                                                            
                        <select class="form-control" id="edit_select">
                            <option value="1">Active</option>
                                <option value="0">Deactive</option>
                            
                        </select>
                    </div>
                </div>
            </div>
            </div>
        </div>
        
        <div class="modal-footer">
            <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary pull-right" onclick="edit_employee_category()">Update</button>
            <input type="hidden" value="{{ request.scheme }}://{{ request.get_host }}/update_employee_category_details/" name="" id="contacturl">
        </div>
        
        
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
  
{% endblock %}